version: 2
jobs:
  build:
    docker:
      - image: chinmaygarde/radar

    steps:
      - restore_cache:
          name: Restore Old Build Artifacts
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-

      - checkout

      - run:
          name: CMake
          command: mkdir -p /tmp/radar/build && cd /tmp/radar/build && cmake .. -G Ninja

      - run:
          name: Build with Ninja
          command: ninja -C /tmp/radar/build

      - save_cache:
          name: Save Build Artifacts
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "/tmp/radar/build"
